version: '3'
services:
  es_wl_vector_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - es_wl_vector_search_volume:/path/in/container
volumes:
  es_wl_vector_search_volume: